### ISSUE TITLE
SickRage Error

### ISSUE THREAD

**Issue by stopmoclay** [ngovil21/RequestChannel.bundle#64]
Having some issues with SickRage integration

So I'm running my plex server on a seedbox, Feral Hosting to be precise, I put in the correct URL for SickRage which is something like

https://HOST.feralhosting.com/USERNAME/sickrage/home/

I've edited the host and username for anonymity sake. 

I then put in my api key which I've generated in SickRage and saved, yet when I save my options in the Plex request channel and attempt to manage SickRage shows or send a show to SickRage, I get an error stating that Plex could not communicate with SickRage.

Any ideas?

**Comment by ngovil21** [comment]
Could you try it without the `/home/` part of the url?

**Comment by stopmoclay** [comment]
I've tried that, still get the same error

**Comment by theCheek** [comment]
Can you post the plexrequests log please?

**Comment by stopmoclay** [comment]
Full log can be found here
[https://pastebin.com/ThWzUPAA](https://pastebin.com/ThWzUPAA)

**Comment by theCheek** [comment]
hmm, @ngovil21 i'm thinking its a json issue due to the following line in the logs:

`2017-07-06 18:31:37,111 (7f5aa28b8700) :  DEBUG (networking:166) - Requesting 'https://host.myserver.com/USERNAME/sickrage/api/0000API000000'
2017-07-06 18:31:37,382 (7f5aa28b8700) :  WARNING (data:179) - Error decoding with simplejson, using demjson instead (this will cause a performance hit) - Expecting value: line 2 column 1 (char 1)`

I've edited the quote to remove personal identifications ( @stopmoclay always do this for logs!). 

Sorry can't help much, but is there a way for you to access it without http**s** ?

Perhaps also the sickrage logs for the same time period would be helpful.

**Comment by stopmoclay** [comment]
Ah my mistake @theCheek I always forget to edit the logs! Thanks for the tip

Gonna be honest, not sure how I'd go about accessing it without https, I'm relatively new at a lot of this but have basic enough skills to install SickRage and CouchPotato, etc. 

Here are the SickRage logs
https://paste.ee/p/34Bdf

**Comment by ngovil21** [comment]
Ya I don't see anything in the logs. This has something to do with how Feral proxies the requests to SickRage. Maybe you can send them a message and see if they can help you find the api url for SickRage.
